### ISSUE TITLE
Saved models for segmentation

### ISSUE THREAD

**Issue by jaan1729** [voldemortX/pytorch-auto-drive#3]
Thanks for implementing all the models in one place. This is so helpful.

I am trying to do inference for segmentation using these models. But, I could not see any link for the trained model. Is there a possibility to share saved models for segmentation also?

**Comment by voldemortX** [comment]
@jaan1729 We just started hosting trained weights when implementing lane detection methods since they are usually quite small.

The segmentation models now only show average performances. But most of the weights should still be on my machine, I'll try to find them and add a `best` performance + download links. It could take a few days though, my files are kind of all mixed up right now and we are kind of focusing resources on lane detection at the moment.

**Comment by jaan1729** [comment]
Thanks for the response @voldemortX. 

I am planning to use deeplab v3 with higher resolution and mixed precision. It would be great if you prioritize it.

**Comment by voldemortX** [comment]
@jaan1729 The deeplabv3 weights corresponding to the performance table is uploaded.
[pascal voc](https://drive.google.com/file/d/1iYN73iqDD74HPZFGorARb6T2w7KkhbPM/view?usp=sharing) 78.17 mIoU
[cityscapes](https://drive.google.com/file/d/1HUR09zcPpjD5Q3LAm4p5t7e9gl1ZkpqU/view?usp=sharing) 70.37 mIoU

**Comment by voldemortX** [comment]
@jaan1729 All segmentation saved model download links are added for the best performance.

**Comment by jaan1729** [comment]
Now, I can see fully helpful segmentation models repo. Thanks! I really appreciate the time and effort you put into this.

**Comment by voldemortX** [comment]
@jaan1729 We now have DeepLabV3 with higher resolution (512x1024) in [model zoo](https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/MODEL_ZOO.md) that may be of interest to you according to our discussions back then.
