### ISSUE TITLE
Curious about the CULane Dataset class

### ISSUE THREAD

**Issue by maomaoding** [voldemortX/pytorch-auto-drive#44]
hi, i'm wondering about the course of ppl,gap and start parameter setting of the CUlane dataset class. As far as i know, CUlane max points is 35, and some start y coordinate is lower than 290. Does those affect the lstr performance? Appreciate your answer.

**Comment by voldemortX** [comment]
@maomaoding We try to follow the 18 ppl setup from SCNN whenever possible, since they created this dataset, and if they assume 290 is the lowest point, then we should not infer otherwise by observing the test labels (one should never infer anything from the test set labels to help their models): https://github.com/XingangPan/SCNN/blob/master/tools/prob2lines/getLane.m

LSTR being a y-sampling method, it can follow this setup so it is aligned with its TuSimple version. Of course you can alternatively sample an arbitrary number of points between the predicted start and end points, although I suspect it can get any better performance, you are encouraged to try.

FYI, you can modify these codes: https://github.com/voldemortX/pytorch-auto-drive/blob/eed417ff0fef46118cab310e69563358bf714b28/torchvision_models/lane_detection/lstr.py#L130
