### ISSUE TITLE
visualize the folder must use provided model？condlanenet？

### ISSUE THREAD

**Issue by hzzzzjzyq** [voldemortX/pytorch-auto-drive#48]
Visualization of a single image can directly use the key point results, but the visualization folder must be inferred once, so I use a model that is not provided, such as condlanenet, and can not infer and can't visualize the folder.
By the way, could you please guide me on the pros and cons of laneaf and condlanenet？thank you very much！

**Comment by voldemortX** [comment]
@hzzzzjzyq You can easily modify the code for the loaded txt visualization of a folder, or naively you can just do this by repeated calling of the python file. We might provide that functionality later when the refactoring is done and the private branch is merged. You are welcomed to submit a pull request if you supported this feature.

As for your question about LaneAF and CondLaneNet, my personal opinion is both of them seem complex pipelines and I doubt their speed when profiled in our settings. If choosing between the two, I'd suggest condlanenet since it is well-received in the community and the FPS of its M model should be around LSTR (I can estimate it around 100 in our hardware by the look of the paper). We may have plan to add condlanenet in the future but no plan is there for laneaf.
