### ISSUE TITLE
demo/inference code?

### ISSUE THREAD

**Issue by karolmajek** [voldemortX/pytorch-auto-drive#7]
Do you plan to provide demo code on external input (not-a-dataset)?
Test-only, on image and/or video?

**Comment by voldemortX** [comment]
@karolmajek Currently we support inference on single image input for segmentation. The dataset setting is only used for coloring/number of classes. But same thing is not supported yet for lane detection. #5 
We'd love to have some interesting demo codes for video file or camera inputs, but I'd make it a low-priority task in Q2, since our Q1 progress is quite behind schedule.

**Comment by voldemortX** [comment]
@karolmajek Segmentation test-only demo with image/folder/video is now supported!
You can refer to [VISUALIZATION.md](https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/VISUALIZATION.md) for details. Note that the demo is based on mmcv, new dependencies are specified at:
https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/INSTALL.md

**Comment by voldemortX** [comment]
Since demos for lane detection & segmentation from image/video inputs are supported, I'll close this now. But do feel free to reopen.
